# push.yml

#  Name of workflow
name: Push workflow

# When workflow is triggered
on:
  push:
    branches:
      - dev
      - main

# Jobs to carry out - these are the jobs github will attempt
jobs:
  deploy: 
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      # Run Test
      - name: Run tests
        run: npm run test
      # Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.veINz3PgzwnWu73r7X7os2RI2Qbyy1VgawYIgDei_ks }}
          NETLIFY_SITE_ID: ${{ secrets.dae2f93f-1d84-47d6-8f55-b061d832f628 }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'